# Generated by Django 3.2.5 on 2021-07-15 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ApiLogic', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test',
        ),
    ]
