# Generated by Django 3.2.5 on 2021-07-15 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApiLogic', '0003_gpsdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhysicalIndicatorsData',
            fields=[
                ('id_connect_device', models.IntegerField(primary_key=True, serialize=False, verbose_name='id')),
                ('data_connect', models.DateTimeField(auto_now=True, verbose_name='дата подключения устройства')),
                ('device_name', models.CharField(max_length=255, verbose_name='имя устройства')),
                ('device_data', models.JSONField(verbose_name='данные с устройства')),
                ('status', models.CharField(max_length=2, verbose_name='статус устройства')),
            ],
        ),
        migrations.CreateModel(
            name='SystemData',
            fields=[
                ('system_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='id')),
                ('date', models.DateTimeField(auto_now=True, verbose_name='дата получения')),
                ('type_process', models.CharField(max_length=20, verbose_name='тип процесса')),
                ('utilization_res', models.IntegerField(verbose_name='используемые ресурсы')),
                ('status', models.CharField(max_length=255, verbose_name='статус')),
                ('action', models.CharField(max_length=255, verbose_name='действие системы')),
            ],
        ),
        migrations.AlterField(
            model_name='gpsdata',
            name='date',
            field=models.DateField(auto_now=True, verbose_name='дата получения gps'),
        ),
    ]
